"""1.2.840.10008.1.2.5 - RLE Lossless"""

INDEX = {
    'emri_small_RLE.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '10'),
        'Rows' : ('US', 64),
        'Columns' : ('US', 64),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 12),
        'HighBit' : ('US', 11),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'emri_small.dcm'),
    },
    'MR_small_RLE.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 64),
        'Columns' : ('US', 64),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 1),
        '_matching_dataset': ('LittleEndianExplicit', 'MR_small.dcm'),
    },
    'OBXXXX1A_rle.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'PALETTE COLOR'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 600),
        'Columns' : ('US', 800),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'OBXXXX1A.dcm'),
    },
    'OBXXXX1A_rle_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'PALETTE COLOR'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 600),
        'Columns' : ('US', 800),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'OBXXXX1A_2frame.dcm'),
    },
    'rtdose_rle.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '15'),
        'Rows' : ('US', 10),
        'Columns' : ('US', 10),
        'BitsAllocated' : ('US', 32),
        'BitsStored' : ('US', 32),
        'HighBit' : ('US', 31),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianImplicit', 'rtdose.dcm'),
    },
    'rtdose_rle_1frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 10),
        'Columns' : ('US', 10),
        'BitsAllocated' : ('US', 32),
        'BitsStored' : ('US', 32),
        'HighBit' : ('US', 31),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianImplicit', 'rtdose_1frame.dcm'),
    },
    'SC_rgb_rle.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'SC_rgb.dcm'),
    },
    'SC_rgb_rle_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'SC_rgb_2frame.dcm'),
    },
    'SC_rgb_rle_16bit.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'SC_rgb_16bit.dcm'),
    },
    'SC_rgb_rle_16bit_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'SC_rgb_16bit_2frame.dcm'),
    },
    'SC_rgb_rle_32bit.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 32),
        'BitsStored' : ('US', 32),
        'HighBit' : ('US', 31),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'SC_rgb_32bit.dcm'),
    },
    'SC_rgb_rle_32bit_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.5'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 32),
        'BitsStored' : ('US', 32),
        'HighBit' : ('US', 31),
        'PixelRepresentation' : ('US', 0),
        '_matching_dataset': ('LittleEndianExplicit', 'SC_rgb_32bit_2frame.dcm'),
    },
}
