"""1.2.840.10008.1.2.1 - Little Endian Explicit VR"""

INDEX = {
    'CT_small.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 128),
        'Columns' : ('US', 128),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 1),
        'RescaleIntercept' : ('DS', '-1024'),
        'RescaleSlope' : ('DS', '1'),
    },
    'emri_small.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '10'),
        'Rows' : ('US', 64),
        'Columns' : ('US', 64),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 12),
        'HighBit' : ('US', 11),
        'PixelRepresentation' : ('US', 0),
    },
    'MR_small.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'MONOCHROME2'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 64),
        'Columns' : ('US', 64),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 1),
        'WindowCenter' : ('DS', '1600'),
        'WindowWidth' : ('DS', '600'),
    },
    'OBXXXX1A.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'PALETTE COLOR'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 600),
        'Columns' : ('US', 800),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
        'ImageComments' : ('LT', 'Contains Palette Color LUT'),
    },
    'OBXXXX1A_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 1),
        'PhotometricInterpretation' : ('CS', 'PALETTE COLOR'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 600),
        'Columns' : ('US', 800),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
        'ImageComments' : ('LT', 'Contains Palette Color LUT'),
    },
    'SC_rgb.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
    },
    'SC_rgb_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 8),
        'BitsStored' : ('US', 8),
        'HighBit' : ('US', 7),
        'PixelRepresentation' : ('US', 0),
    },
    'SC_rgb_16bit.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 0),
    },
    'SC_rgb_16bit_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 16),
        'BitsStored' : ('US', 16),
        'HighBit' : ('US', 15),
        'PixelRepresentation' : ('US', 0),
    },
    'SC_rgb_32bit.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '1'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 32),
        'BitsStored' : ('US', 32),
        'HighBit' : ('US', 31),
        'PixelRepresentation' : ('US', 0),
    },
    'SC_rgb_32bit_2frame.dcm' : {
        'TransferSyntaxUID' : ('UI', '1.2.840.10008.1.2.1'),
        'SamplesPerPixel' : ('US', 3),
        'PhotometricInterpretation' : ('CS', 'RGB'),
        'PlanarConfiguration' : ('US', 0),
        'NumberOfFrames' : ('IS', '2'),
        'Rows' : ('US', 100),
        'Columns' : ('US', 100),
        'BitsAllocated' : ('US', 32),
        'BitsStored' : ('US', 32),
        'HighBit' : ('US', 31),
        'PixelRepresentation' : ('US', 0),
    },
}
